SHORT MESSAGE Fixed homepage scrolling overflow-x
LONG MESSAGE
I fixed the horizontal scrolling in the code and made little adjustment
to the v shape in the footer section.

Error: When scrollbar is activated from the index.html the homepage
shows scrollbar at  the bottom of the page which makes it scroll
horizontally.